### ISSUE TITLE
Textdomain Constant?

### ISSUE THREAD

**Issue by robneu** [NateWr/business-profile#10]
I was wondering if you've run into any issues using a constant for the textdomain rather than hard-coding it? It's my understanding that this can cause problems with programs like GNU Gettext.

Reference: https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

**Comment by NateWr** [comment]
I know, it's terrible! An old mistake I haven't yet corrected. It's on my todo list. I just need to implement the backwards compatibility handler as I did [like this](https://github.com/NateWr/restaurant-reservations/blob/master/includes/Compatibility.class.php) in another plugin. It's [fairly simple](https://github.com/NateWr/restaurant-reservations/commit/5b4c7194f6d33d2756d76d1c79659096ea380d16), just need to actually do it. :)

**Comment by NateWr** [comment]
PRs welcome of course. ;)
