### ISSUE TITLE
WordPress.org install doesn't include translation files

### ISSUE THREAD

**Issue by lmartins** [NateWr/business-profile#18]
Hi,

I was looking to have the plugin translated to Portuguese and Im seeing that it already has translation files for that, although those files aren't included when installing the plugin from wordpress.org.

Anything can be done about this?

Cheers.

**Comment by NateWr** [comment]
Hey @lmartins, I haven't put out a new version of the plugin since merging your translation files. They'll definitely go out with the next update, but I don't know when that will be.

**Comment by lmartins** [comment]
Ahh ok, got it.
Thanks.
