### ISSUE TITLE
Map Showing When Not Set

### ISSUE THREAD

**Issue by neilgee** [NateWr/business-profile#24]
I have not set the map co-ords, but still getting a map shown when using the shortcode on a page. 

Example - http://dev.fitmum.autopilotyourbusiness.com/contact/ It seems to be match based on the company name - but these are matching companies from different countries.

**Comment by NateWr** [comment]
Hi Neil,

The shortcode comes with several attributes for controlling the visibility of the different components. Try ```[contact-card show_map=0]```.

You can find all the attributes detailed in the help doc, which you can find under the plugin's name in the list of plugins in your WordPress admin panel.

Probably worth surfacing this better when we handle #23.

Might be nice to automatically not show some things if data is missing too.

**Comment by neilgee** [comment]
Hi Nate, cool thanks, oops missed the help doc, agree with not displaying if empty.
