### ISSUE TITLE
"Get Directions" Link to include option to open in new window/tab.

### ISSUE THREAD

**Issue by lloydrogerspencer** [NateWr/business-profile#30]
Currently the Google Map **"Get directions"** link opens in a new window/tab within the browser.

However this is not the case for the "Get Directions" links in:
1. Contact Card Widget.
2. Selected Contact Page.

Solution:
An option to have the links open in a new window/tab would be nice.

**Comment by NateWr** [comment]
Hey Lloyd, I'm pretty militant about keeping options minimal. And I usually abhor links opening in new tabs. But I think this is probably a case where a `target="_blank"` is justified, so I'll flag this as an enhancement to open in a new tab by default.

If you need something more urgent let me know and I can show you how to use the filters to override the output.
