### ISSUE TITLE
google map

### ISSUE THREAD

**Issue by kli0** [NateWr/business-profile#5]
Hello,
our store is enlisted in google maps, but providing an address in site does not match the map. Can I manually set the coordinates? or how can I match the google list?

**Comment by NateWr** [comment]
Hi @kli0,

This is an unfortunate circumstance that happens to some businesses, if your postal address doesn't match your actual location on Google Maps. There's no easy workaround for this. However, if you're familiar with using the Developer Tools in your browser to manipulate the DOM, I can describe a hackish workaround you can use to manually set the coordinates.

**Comment by kli0** [comment]
Thanks Nate, if you tell me where to look for, I think I may manage to

**Comment by NateWr** [comment]
Ok,  First, retrieve the coordinates you want from Google:

1. Go to Google Maps and right click on the place where your business is.

2. From the menu, select "What's here?"

3. When you select that, the lat/lon coordinates will appear under the address in the top left. Copy those down.

Now go into your Business Profile settings in WordPress. I'll give you instructions for this section using the Google Chrome browser but if you're familiar with using the dev tools of another browser you should be able to do the same thing.

1. Enter the address of your business and click Retrieve Map Coordinates.

2. Right click on the coordinates and select Inspect Element. In the panel on the right you'll see the HTML elements. Find the two hidden input fields named `bpfwp-settings[address][lat]` and `bpfwp-settings[address][lon]`.

![manually-set-coords](https://cloud.githubusercontent.com/assets/2306629/5663649/9156ce94-9741-11e4-90bf-67a2b2d3767a.png)

3. Double-click on the value of each field and paste in the lat/lon values you copied from Google.

4. Click the save button at the bottom of the page.

Now you should have all the data you need saved: a human-readable address and the correct lat/lon values. Just know that if you ever update the address again it will overwrite the lat/lon values and you'll need to do this again.

**Comment by kli0** [comment]
done, thanks a lot :)
