### ISSUE TITLE
non-object PHP notice error

### ISSUE THREAD

**Issue by neilgee** [NateWr/business-profile#55]
Being output in WP 4.5.2 & BP 1.1
`Notice: Trying to get property of non-object in /srv/www/allwater/htdocs/wp-content/plugins/business-profile/business-profile.php on line 207`

**Comment by NateWr** [comment]
Thanks for reporting Neil. It looks like this is possible if multiple locations are not enabled. 

Note to self: need to check `isset()` on `$bpfwp_controller->cpts` before relying on it.
