### ISSUE TITLE
Define custom post type for multiple locations

### ISSUE THREAD

**Issue by NateWr** [NateWr/business-profile#7]
Multiple locations will be defined in a `location` custom post type that follows the (work-in-progress) [standard](https://github.com/justintadlock/content-type-standards/issues/25) as closely as possible. The custom post types should be "activated" through a toggle in the main profile settings page. When activated, menu items for Locations and Add Locations will appear under the Business Profile link.

- [x] Set up code architecture for Custom Post Type
- [x] Add toggle to settings page to "enable" custom post type
- [x] Add menu items to Business Profile tab

Previous discussion can be found in #6.

**Comment by NateWr** [comment]
a173666f7cfac3cc961fc990c1ee534503b3aab7 and 037622276915e464f168aaf39cbf7fab2a9bb778 put the basics in place for the `location` post type. There's still a lot of fleshing out to be done, but let me know if you have any concerns at this stage @robnue.

**Comment by NateWr** [comment]
The `post_meta` keys need to be updated to comply with changes in the use of underscores in the content type standards project. See [discussion](https://github.com/justintadlock/content-type-standards/issues/24) and the [updated standard](https://github.com/justintadlock/content-type-standards/issues/25).

**Comment by franz-josef-kaiser** [comment]
Ehm, @NateWr – could you please keep such commits on feature or issue branches and not on `master`? Example: `issue-7-multiple-locations`. Thanks!

**Comment by NateWr** [comment]
@franz-josef-kaiser See the [multiple-locations](https://github.com/NateWr/business-profile/tree/multiple-locations) branch.

**Comment by NateWr** [comment]
CPTs defined. Further work being done in #8 and #9.
