### ISSUE TITLE
Image buttons are not translatable

### ISSUE THREAD

**Issue by lucspe** [NateWr/business-profile#74]
I think this has to do with Simple Admin Pages class rather, but honestly no idea what's the problem :-) 

@NateWr  Do you have any clues?

**Comment by NateWr** [comment]
Because I accidentally used the wrong textdomain.

https://github.com/NateWr/business-profile/blob/master/includes/class-settings.php#L282-L284

Oops.

**Comment by lucspe** [comment]
I obviously missed looking at the most obvious explanation. Anyways, I've changed that now (see #75)
