### ISSUE TITLE
Add/Edit locations

### ISSUE THREAD

**Issue by NateWr** [NateWr/business-profile#8]
The add/edit interface for `location` posts should support post meta in the format described in the [locations standard](https://github.com/justintadlock/content-type-standards/issues/25).

- [x] Remove unnecessary components from the add/edit page
- [x] Convert scheduler.js from Simple Admin Pages for use as post meta for opening hours
- [x] Convert address.js from Simple Admin Pages for use as post meta for business address (lat/lon lookup)
- [x] Support all the rest of the post meta required

Previous discussion in #6.

**Comment by NateWr** [comment]
I set up `_location_phone` as the post meta, according to the [specification](https://github.com/justintadlock/content-type-standards/issues/25) I set out. However, it looks like the general standard [may be changing](https://github.com/justintadlock/content-type-standards/issues/29). Take a look and let's decide on whether or not to change it so when you implement post meta we can get it right the first time.

**Comment by NateWr** [comment]
I went ahead and removed the post type slug from the existing post meta. Be sure to check out the [specification](https://github.com/justintadlock/content-type-standards/issues/25) for fuller details.

**Comment by franz-josef-kaiser** [comment]
Please @NateWr read the part [about underscore prefixes](https://github.com/justintadlock/content-type-standards/wiki/Post-Metadata#a-note-on-using-an-underscore-prefix-for-keys) in the "content type standards" repo. :)

**Comment by NateWr** [comment]
@franz-josef-kaiser The commit last week (#8417591) removes the underscore prefix and the [standard](https://github.com/justintadlock/content-type-standards/issues/25) was updated as well.
