### ISSUE TITLE
Misspelled Swedish translation for word 'Get Direction'

### ISSUE THREAD

**Issue by callebokedal** [NateWr/business-profile#80]
In file:
`business-profile/languages/business-profile-sv_SE.po`

There is a misspelled word (see 'msgstr' on row 594):

```
...
#: includes/template-functions.php:560
msgid "Get Directions"
msgstr "Vägbeskriving"
...
```

Should be:
```msgstr "Vägbeskrivning"```

An "n" is missing today...

**Comment by callebokedal** [comment]
Added pull request to solve this. Unsure if more changes needs to be made (only updated the .po file).
BR Calle

**Comment by NateWr** [comment]
Merged.
