### ISSUE TITLE
Add support for non-address businesses

### ISSUE THREAD

**Issue by andrewm57** [NateWr/business-profile#86]
I think areaServed would help local businesses without a physical location.
> AdministrativeArea > can't see anything but entering (multiple) text strings for city/county/state/etc.
> GeoShape > radius from center point, or cooler would be a map drawing tool that creates lat/lon shapes

**Comment by NateWr** [comment]
I aim to keep the setup and configuration as minimal as possible, so I probably won't add this setting. But this code will give you a quick rundown of how you can add additional fields:

https://gist.github.com/NateWr/b28bb63ba8a73bb14eac#file-construction-for-bp-php-L62-L92

You can then use the custom templates feature to add in the schema details:

http://doc.themeofthecrop.com/plugins/business-profile/developer/templates
