### ISSUE TITLE
Extend [contact-card] to support multiple locations

### ISSUE THREAD

**Issue by NateWr** [NateWr/business-profile#9]
The `[contact-card]` shortcode needs to be able to handle multiple locations. It should also use a template loading technique as discussed in #6.

- [x] Add support for `location` arg (use post ID) https://github.com/NateWr/business-profile/commit/f2558b9c41b540cecce27fab79ad2f56c64f68c5
- [x] Add support for [loading templates](https://github.com/NateWr/business-profile/issues/6#issuecomment-87098362)
- [x] Extend widget to support location selection

**Comment by robneu** [comment]
🎉
